name: DomainWhitelist
version: 1.0
main: lol.house1.newdomainwhitelist.DomainWhitelistPlugin
description: A plugin that allows you to whitelist specific domains and customize their MOTD and server icon.
author: House 1 and ChatGPT

commands:
  whitelist:
    description: Whitelist a domain
    usage: /whitelist <domain>

permissions:
  domainwhitelist.whitelist:
    description: Allows players to whitelist a domain
    default: op